---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1
  labels:
    app: project-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-1
  template:
    metadata:
      labels:
        app: project-1
    spec:
      containers:
      - name: project-1
        image: echo:1
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: project-1
  labels:
    app: project-1
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: project-1
